### ISSUE TITLE
Image rending in lesson 07 integration (part 3)

### ISSUE THREAD

**Issue by dotsdl** [ASU-CompMethodsPhysics-PHY494/PHY494-resources#3]
It looks like the images linked in the [lesson 07: integration (part 3)](https://github.com/ASU-CompMethodsPhysics-PHY494/PHY494-resources/blob/master/07_integration/07_integration-part-3.ipynb) notebook weren't committed to the [images](https://github.com/ASU-CompMethodsPhysics-PHY494/PHY494-resources/tree/master/07_integration/images) directory.

Also, the YouTube video widget doesn't show up. I think this might be because widget state isn't preserved by the notebook format, but I could be wrong. In that case then perhaps also add a clickable link above it.

**Comment by orbeckst** [comment]
The images show up now but the YT is not shown. If it were crucial I would include a clickable link but in this case it's not worth it. But good to know. 

The reason why the YT is not include is because I never saved any state with the student notebook.

In contrast, the full slide show http://nbviewer.jupyter.org/format/slides/github/ASU-CompMethodsPhysics-PHY494/PHY494-resources/blob/master/07_integration/07_integration.ipynb#/ has the video running because it was saved with state. Subtle.
